### ISSUE TITLE
Saving Capture Screen as a Template

### ISSUE THREAD

**Issue by edwardwilliampenn** [tabulapdf/tabula#608]
Hi,

We are looking for grab data (words or numbers) from various fields on the Schedule K-1 (Form 1065) that we receive from organizations.  I can select all the fields in a file and then convert the data, but since the next file will be the same is there a way to save that setup as a template that can then grab the same data fields from succeeding (and later, future) documents, rather than have to re-select all the same fields?

Thanks,
Ed

**Comment by jeremybmerrill** [comment]
Hi @edwardwilliampenn:

At the moment, no. 

That's basically the next thing on the list to implement in the Tabula frontend. The pieces are all there, it's just gotta get done. (Cross-referencingSee #483, #505 and #93.)

You can, however, use the [tabula-java](https://github.com/tabulapdf/tabula-java) command-line app to do approximately this: by downloading the "script" extraction option from Tabula, then calling the resulting shell/bash file with each K1 form as the argument on the command-line. See #505 for instructions (and if anything's unclear, feel free to reply here).

**Comment by edwardwilliampenn** [comment]
Hi,

                Have not had a chance before to work on this, but noticing something else that could be an issue:  if I select an empty cell, the conversion returns an error.  On the form there are about 20 cells that we want to capture, but different ones are blank on different submissions from organizations – it looks like blank cells return an error; we’d like them to return 0 or blank, so is there a way to do that?

Thanks,
Ed



Edward Wagner
IT Manager
William Penn Foundation
Two Logan Square, 11th Floor
Philadelphia, PA 19103
215-988-1830
ewagner@williampennfoundation.org<mailto:ewagner@williampennfoundation.org>
[cid:image001.png@01D1957E.E4D5A680]<https://twitter.com/WilliamPennFdn>
[cid:image001.jpg@01CFFCC8.4984EA60]<http://www.williampennfoundation.org/>

**Comment by jeremybmerrill** [comment]
Hi @edwardwilliampenn, it's a known issue. It'll be fixed in the next official release of Tabula. For now, I can get you an unofficial build that will properly handle blank cells (returning an empty string). Which platform are you using? (Mac/Win/Linux)

**Comment by edwardwilliampenn** [comment]
Hi,

                I am on the Windows (7) platform.

Thanks,
Ed



Edward Wagner
IT Manager
William Penn Foundation
Two Logan Square, 11th Floor
Philadelphia, PA 19103
215-988-1830
ewagner@williampennfoundation.org<mailto:ewagner@williampennfoundation.org>
[cid:image001.png@01D1957E.E4D5A680]<https://twitter.com/WilliamPennFdn>
[cid:image001.jpg@01CFFCC8.4984EA60]<http://www.williampennfoundation.org/>

**Comment by jeremybmerrill** [comment]
@edwardwilliampenn  give this a shot: https://www.dropbox.com/s/ga92sdlpyjsiwqu/tabula-win-rev4860c428a4e50d2cac5ac02e43ee194f54e7dd28.zip?dl=0

**Comment by edwardwilliampenn** [comment]
Thanks, I will give it a try!



Edward Wagner
IT Manager
William Penn Foundation
Two Logan Square, 11th Floor
Philadelphia, PA 19103
215-988-1830
ewagner@williampennfoundation.org<mailto:ewagner@williampennfoundation.org>
[cid:image001.png@01D1957E.E4D5A680]<https://twitter.com/WilliamPennFdn>
[cid:image001.jpg@01CFFCC8.4984EA60]<http://www.williampennfoundation.org/>

**Comment by edwardwilliampenn** [comment]
Hi,

                Just tried it and still get the error (see below) with an empty data cell.  When I remove that cell, it works fine.

Ed

[cid:image001.png@01D27E36.EF6E4240]

[cid:image002.png@01D27E36.EF6E4240]

Edward Wagner
IT Manager
William Penn Foundation
Two Logan Square, 11th Floor
Philadelphia, PA 19103
215-988-1830
ewagner@williampennfoundation.org<mailto:ewagner@williampennfoundation.org>
[cid:image001.png@01D1957E.E4D5A680]<https://twitter.com/WilliamPennFdn>
[cid:image001.jpg@01CFFCC8.4984EA60]<http://www.williampennfoundation.org/>

**Comment by jeremybmerrill** [comment]
Hmm, sorry about that. Those screenshots aren't coming through. Can you post them via the Github interface?

**Comment by edwardwilliampenn** [comment]
Here is the section of the form (with arrow pointing to empty cell) and the error msg

![errormsg](https://cloud.githubusercontent.com/assets/25041971/22609311/ba666082-ea2e-11e6-8a16-1657d6e80202.jpg)
![form](https://cloud.githubusercontent.com/assets/25041971/22609312/ba6df93c-ea2e-11e6-9299-c44960e5b292.jpg)

**Comment by jeremybmerrill** [comment]
@edwardwilliampenn I'm a little puzzled by this, but it's possible that the test version I sent you was a little bit out of date and therefore missed the fix that should've fixed this issue., I baked another Tabula Windows version. Can you give that a try? https://www.dropbox.com/s/s8atvhzsa7yajhy/tabula-win-rev1b02f31c8623f670a9edb86f5cacd2fe406b6dd5.zip?dl=0

**Comment by edwardwilliampenn** [comment]
This one works!

Edward Wagner
IT Manager
William Penn Foundation
Two Logan Square, 11th Floor
Philadelphia, PA 19103
215-988-1830
ewagner@williampennfoundation.org<mailto:ewagner@williampennfoundation.org>
[cid:image001.png@01D1957E.E4D5A680]<https://twitter.com/WilliamPennFdn>
[cid:image001.jpg@01CFFCC8.4984EA60]<http://www.williampennfoundation.org/>

**Comment by jeremybmerrill** [comment]
Hooray and phew!

**Comment by edwardwilliampenn** [comment]
Now to work on creating a template so that the selected cell layout can be saved and reused on other files.

Feel free to release this enhancement anytime it’s ready!



Edward Wagner
IT Manager
William Penn Foundation
Two Logan Square, 11th Floor
Philadelphia, PA 19103
215-988-1830
ewagner@williampennfoundation.org<mailto:ewagner@williampennfoundation.org>
[cid:image001.png@01D1957E.E4D5A680]<https://twitter.com/WilliamPennFdn>
[cid:image001.jpg@01CFFCC8.4984EA60]<http://www.williampennfoundation.org/>

**Comment by jeremybmerrill** [comment]
I'm working' on it. I'm not the one with the signing keys to make a new release, hence the one hosted in my dropbox. :)

**Comment by jeremybmerrill** [comment]
cc @mtigas
